name: Build
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * *" # daily at midnight
  workflow_dispatch:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        tools: [mongoimport, mongoexport, mongodump, mongorestore, bsondump, mongostat, mongotop, mongofiles]
    runs-on: ${{ matrix.os }}
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      - name: install_go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: mongodump --version
