name: Lint

on:
  push:
    branch:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  lint-shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: luizm/action-sh-checker@v0.1.8
      env:
        SHELLCHECK_OPTS: "-x bin"
        SHFMT_OPTS: "-d -i 2 -ci bin"
      with:
        sh_checker_checkbashisms_enable: true
